//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mpcstats.My {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class MySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MySettings defaultInstance = ((MySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MySettings())));
        
        public static MySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:13579/status.html")]
        public string url {
            get {
                return ((string)(this["url"]));
            }
            set {
                this["url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>3g2</string>\r\n  <string>3gp</string>\r\n  <string>3gp2</string>\r\n  <string>3" +
            "gpp</string>\r\n  <string>aac</string>\r\n  <string>aif</string>\r\n  <string>aifc</st" +
            "ring>\r\n  <string>aiff</string>\r\n  <string>amr</string>\r\n  <string>amv</string>\r\n" +
            "  <string>asf</string>\r\n  <string>asx</string>\r\n  <string>au</string>\r\n  <string" +
            ">avi</string>\r\n  <string>bik</string>\r\n  <string>bmp</string>\r\n  <string>cda</st" +
            "ring>\r\n  <string>d2v</string>\r\n  <string>dat</string>\r\n  <string>dib</string>\r\n " +
            " <string>divx</string>\r\n  <string>drc</string>\r\n  <string>dsa</string>\r\n  <strin" +
            "g>dsm</string>\r\n  <string>dss</string>\r\n  <string>dsv</string>\r\n  <string>dvda</" +
            "string>\r\n  <string>dvdf</string>\r\n  <string>evo</string>\r\n  <string>flc</string>" +
            "\r\n  <string>fli</string>\r\n  <string>flic</string>\r\n  <string>flv</string>\r\n  <st" +
            "ring>gif</string>\r\n  <string>hdmov</string>\r\n  <string>ivf</string>\r\n  <string>j" +
            "peg</string>\r\n  <string>jpg</string>\r\n  <string>m1a</string>\r\n  <string>m1v</str" +
            "ing>\r\n  <string>m2a</string>\r\n  <string>m2ts</string>\r\n  <string>m2v</string>\r\n " +
            " <string>m3u</string>\r\n  <string>m4a</string>\r\n  <string>m4b</string>\r\n  <string" +
            ">m4v</string>\r\n  <string>mid</string>\r\n  <string>midi</string>\r\n  <string>mka</s" +
            "tring>\r\n  <string>mkv</string>\r\n  <string>mov</string>\r\n  <string>mp2</string>\r\n" +
            "  <string>mp2v</string>\r\n  <string>mp3</string>\r\n  <string>mp4</string>\r\n  <stri" +
            "ng>mpa</string>\r\n  <string>mpc</string>\r\n  <string>mpcpl</string>\r\n  <string>mpe" +
            "</string>\r\n  <string>mpeg</string>\r\n  <string>mpg</string>\r\n  <string>mpv2</stri" +
            "ng>\r\n  <string>ogg</string>\r\n  <string>ogm</string>\r\n  <string>pic</string>\r\n  <" +
            "string>pls</string>\r\n  <string>png</string>\r\n  <string>pss</string>\r\n  <string>p" +
            "va</string>\r\n  <string>qt</string>\r\n  <string>ra</string>\r\n  <string>ram</string" +
            ">\r\n  <string>ratdvd</string>\r\n  <string>rm</string>\r\n  <string>rmi</string>\r\n  <" +
            "string>rmm</string>\r\n  <string>rmvb</string>\r\n  <string>rnx</string>\r\n  <string>" +
            "roq</string>\r\n  <string>rp</string>\r\n  <string>rpm</string>\r\n  <string>rt</strin" +
            "g>\r\n  <string>smi</string>\r\n  <string>smil</string>\r\n  <string>smk</string>\r\n  <" +
            "string>snd</string>\r\n  <string>swf</string>\r\n  <string>tif</string>\r\n  <string>t" +
            "iff</string>\r\n  <string>tp</string>\r\n  <string>tpr</string>\r\n  <string>ts</strin" +
            "g>\r\n  <string>vp6</string>\r\n  <string>wav</string>\r\n  <string>wax</string>\r\n  <s" +
            "tring>wm</string>\r\n  <string>wma</string>\r\n  <string>wmp</string>\r\n  <string>wmv" +
            "</string>\r\n  <string>wmx</string>\r\n  <string>wvx</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection file_types {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["file_types"]));
            }
            set {
                this["file_types"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>pdtv</string>
  <string>vtv</string>
  <string>eztv</string>
  <string>ws</string>
  <string>hdtv</string>
  <string>preair</string>
  <string>ts</string>
  <string>tvrip</string>
  <string>dsrip</string>
  <string>hr</string>
  <string>lol</string>
  <string>loki</string>
  <string>tcm</string>
  <string>xor</string>
  <string>fqm</string>
  <string>umd</string>
  <string>tbs</string>
  <string>ctu</string>
  <string>divx</string>
  <string>ac3</string>
  <string>repack</string>
  <string>proper</string>
  <string>vcd</string>
  <string>svcd</string>
  <string>tc</string>
  <string>dvdscr</string>
  <string>r5</string>
  <string>dvdrip</string>
  <string>wp</string>
  <string>fs</string>
  <string>sdtv</string>
  <string>dvb</string>
  <string>ppv</string>
  <string>h</string>
  <string>h720p</string>
  <string>h480p</string>
  <string>h1080p</string>
  <string>h</string>
  <string>264</string>
  <string>h264</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection cruft {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cruft"]));
            }
            set {
                this["cruft"] = value;
            }
        }
    }
}
